<a href="https://colab.research.google.com/github/santhoshml/python-practice/blob/main/filter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
np1=np.arange(1,10)
np1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
x= [True, True, False, True, True, False, True, True, False]

In [9]:
np1[x]

array([1, 2, 4, 5, 7, 8])

In [11]:
filtered = []
for thing in np1:
    if thing % 2 ==0 :
        filtered.append(True)
    else :
        filtered.append(False)

In [12]:
np1[filtered]

array([2, 4, 6, 8])

In [14]:
filtered = np1 % 2 == 0
filtered

array([False,  True, False,  True, False,  True, False,  True, False])