<a href="https://colab.research.google.com/github/santhoshml/python-practice/blob/main/functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
np1=np.arange(10)
np1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.sqrt(np1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [6]:
np.cos(np1)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [7]:
np.exp(np1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [8]:
np.min(np1)

0

In [9]:
np.max(np1)

9

In [10]:
np.sign(np1)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [11]:
np.log(np1)

<ipython-input-11-b6365e7fa858>:1: RuntimeWarning: divide by zero encountered in log
  np.log(np1)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [12]:
np.reciprocal(np1)

<ipython-input-12-8da9aea2259c>:1: RuntimeWarning: divide by zero encountered in reciprocal
  np.reciprocal(np1)
<ipython-input-12-8da9aea2259c>:1: RuntimeWarning: invalid value encountered in reciprocal
  np.reciprocal(np1)


array([-9223372036854775808,                    1,                    0,
                          0,                    0,                    0,
                          0,                    0,                    0,
                          0])