<a href="https://colab.research.google.com/github/santhoshml/python-practice/blob/main/Iterator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
np1=np.arange(10)
np1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
for x in np1:
    print(x)

0
1
2
3
4
5
6
7
8
9


In [6]:
np2=np.array([[1,2,3, 4, 5],[6, 7, 8, 9, 10]])
np2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
np3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
np3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [8]:
for x in np.nditer(np3):
    print(x)

1
2
3
4
5
6
7
8
9


In [9]:
for x in np.nditer(np2):
    print(x)

1
2
3
4
5
6
7
8
9
10
