<a href="https://colab.research.google.com/github/santhoshml/python-practice/blob/main/numpy-intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

In [2]:
import numpy as np
#

In [3]:
np1=np.array([1,2,3, 4, 5, 6, 7, 8, 9, 0])
np1

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [4]:
np1.shape

(10,)

In [5]:
np2=np.arange(10)
np2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np3=np.arange(0, 10, 2)
np3

array([0, 2, 4, 6, 8])

In [8]:
np4=np.zeros(10)
np4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np5=np.ones(5)
np5

array([1., 1., 1., 1., 1.])

In [10]:
np6=np.linspace(0, 10, 5)
np6

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
np7=np.zeros((2, 10))
print(np7.shape)
np7

(2, 10)


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
np8=np.full((2, 10), 5)
np8

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [16]:
list=[1, 2, 3, 4]
np9=np.array(list)
print(np9.dtype)
np9


int64


array([1, 2, 3, 4])