<a href="https://colab.research.google.com/github/santhoshml/python-practice/blob/main/search.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

In [9]:
np1=np.array([1,2,3, 4, 65,7, 8, 9, 3])
np1

array([ 1,  2,  3,  4, 65,  7,  8,  9,  3])

In [10]:
x=np.where(np1==3)
x

(array([2, 8]),)

In [12]:
x[0]

array([2, 8])

In [14]:
y=np.where(np1 %2==0)
y


(array([1, 3, 6]),)

In [19]:
y[0].shape

(3,)