<a href="https://colab.research.google.com/github/santhoshml/python-practice/blob/main/shape_reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy  as np

In [4]:
np1=np.arange(1,13)
np1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
np1.shape

(12,)

In [7]:
np3=np1.reshape(3,4)
np3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
np4=np1.reshape(2, 3,2)
np4

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [12]:
np5=np4.reshape(-1)
np5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])