<a href="https://colab.research.google.com/github/santhoshml/python-practice/blob/main/slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
np1=np.arange(1,10)
np1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np1[1:5]

array([2, 3, 4, 5])

In [6]:
np1[3:]

array([4, 5, 6, 7, 8, 9])

In [7]:
np1[-3:-1]

array([7, 8])

In [8]:
np1[1:5:2]

array([2, 4])

In [9]:
np1[::2]

array([1, 3, 5, 7, 9])

In [10]:
np1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [12]:
np1[5:1:-1]

array([6, 5, 4, 3])

In [23]:
np2=np.full((2, 10), 5)
np2
np2=np.array([[1,2,3,4,5], [6,7,8,9,10]])
np2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [24]:
np2[1,2]

8

In [26]:
np2[0:, 1:3]

array([[2, 3],
       [7, 8]])