<a href="https://colab.research.google.com/github/santhoshml/python-practice/blob/main/sort.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
np1=np.array([6,7,4,9,0,1])
np1

array([6, 7, 4, 9, 0, 1])

In [5]:
np.sort(np1)

array([0, 1, 4, 6, 7, 9])

In [8]:
np2=np.array(['john', 'tina', 'erin', 'tim'])
np2

array(['john', 'tina', 'erin', 'tim'], dtype='<U4')

In [9]:
np.sort(np2)

array(['erin', 'john', 'tim', 'tina'], dtype='<U4')

In [11]:
np4=np.array([[6,8,3,1], [4,7,1,0]])
np4

array([[6, 8, 3, 1],
       [4, 7, 1, 0]])

In [12]:
np.sort(np4)

array([[1, 3, 6, 8],
       [0, 1, 4, 7]])